version: "3.8"

services:
  bountybot:
    container_name: fracture-bounty-bot
    build: .
    environment:
      - DISCORD_TOKEN
      - OWNER_ID
      - TEST_GUILD_ID
      - DATA_FILE=bounties.json
    volumes:
      - ./bounties.json:/app/bounties.json
    restart: unless-stopped
